# Generated by Django 4.1.7 on 2023-05-26 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_name_alter_question_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checktest',
            old_name='finded_question',
            new_name='finded_questions',
        ),
        migrations.RenameField(
            model_name='checktest',
            old_name='persentage',
            new_name='percentage',
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 12, 42, 27, 114484, tzinfo=datetime.timezone.utc)),
        ),
    ]
