# Generated by Django 4.1.7 on 2023-05-28 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_finded_question_checktest_finded_questions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkquestion',
            old_name='checkTest',
            new_name='checktest',
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 11, 9, 17, 372504, tzinfo=datetime.timezone.utc)),
        ),
    ]
