# Generated by Django 4.1.7 on 2023-05-28 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_checktest_checkquestion_checktest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 11, 31, 54, 224865, tzinfo=datetime.timezone.utc)),
        ),
    ]
