# Generated by Django 4.2.7 on 2023-11-05 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 14, 27, 40, 853929, tzinfo=datetime.timezone.utc)),
        ),
    ]
